version: '3'
services:
  ros2_dev:
    build: .
    container_name: ros2_dev
    volumes:
      - .:/workspace
      - ./ros2_ws:/workspace/ros2_ws
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
    command: tail -f /dev/null 